### ISSUE TITLE
AttrOptions Changes

### ISSUE THREAD

**Issue by chadstolper** [chadstolper/DGLOs#25]
DGLOs.ts line 13 and DGLOsSVGBaseClass.ts line 137
TODO: map of variables/attrs:
- fill
- stroke
- stroke-width
- radius
- opacity
- width, height

**Comment by chadstolper** [comment]
Create independent NodeAttrOpts from EdgeAttrOpts interfaces, then SVGNode/EdgeAttrOpts that extend those.

**Comment by Sanfordm** [comment]
currently two options:

1. split into two, one for nodes and edges
2. remains as one, but expanded and reorganized to work for either edges or nodes at anytime. hopefully

**Comment by Sanfordm** [comment]
TODO: combine specialized attropts to single

**Comment by Sanfordm** [comment]
AttrOpts v3 changes:

- setNodeAttributes and setEdgeAttributes replaced with single setAttributes dglo.
- SVGAttrOpts now holds data for both nodes and edges.
- AttrOpts interface exported from DGLOs removed.
- Most attribute setting in code moved to fit new scheme.
- LabelGlyphShape hardcoded with black stroke.
- MatrixAttrOpts and Label hardcoding only remaining "issue"(?).
