### ISSUE TITLE
Width of Text Calculation

### ISSUE THREAD

**Issue by chadstolper** [chadstolper/DGLOs#30]
`ret = n.label.length * 4;` //TODO: replace # with font related function
DGLOsMatt.ts line 148

**Comment by Sanfordm** [comment]
working with changes to attrOpts v2

**Comment by Sanfordm** [comment]
might need to include an option for tightness of label collision radius.

**Comment by Sanfordm** [comment]
need to create a get and set for collision tightness, get and set for option to apply strength by weight and option to apply collision by label

**Comment by Sanfordm** [comment]
addition of simulationattropts to define certain parameters for the user implemented.
issue resolved.
